pending_image_requests = {}
pending_video_requests = {}
pending_media_groups = {}
user_text_cooldowns = {}
user_image_cooldowns = {}
user_video_cooldowns = {}
full_access_image_cooldowns = {}
paid_unlimited_until = {}
pending_prompt_requests = {}
pending_nsfw_configs = {}
pending_tts_requests = {}
pending_tts_configs = {}
pending_file_tasks = {}
tts_voice_previews = {}
generated_draw_messages = {}
chat_members_cache: dict = {}
daily_gen_limits: dict = {}
banned_user_ids: set = set()
chat_custom_limits: dict = {}
dual_histories: dict = {}
dual_tasks: dict = {}
generated_code_messages: dict = {}
chat_context_buffer: dict = {}  # chat_id -> list[str], все сообщения чата (не только боту)
chat_last_files: dict = {}  # chat_id -> {"filename": str, "data": bytes, "ts": float}
